<a href="https://colab.research.google.com/github/nishultomar/TensorflowExercises/blob/master/TF_Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [5]:
hello = tf.constant("HELLO")
hello

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [7]:
world = tf.constant("World")
type(world)

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [11]:
print(result)

b'HELLOWorld'


In [0]:
var1 = tf.constant(10)
var2 = tf.constant(30)

In [13]:
var1+var2

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [0]:
with tf.Session() as sess:
  result = sess.run(var1+var2)

In [18]:
result

40

In [0]:
constant = tf.constant(10)

In [0]:
mat_1 = tf.fill((5,5),10)

In [0]:
zeros = tf.zeros((5,5))

In [0]:
ones = tf.ones((5,5))

In [0]:
randn = tf.random_normal((4,4),mean=0,stddev=0.1)

In [0]:
randuni = tf.random_uniform((4,4),minval=0,maxval=1)

In [0]:
myops=[constant,mat_1,zeros,ones,randn,randuni]

In [0]:
sess = tf.InteractiveSession()

In [32]:
for op in myops:
  #print(sess.run(op))
  print(op.eval())
  print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[-0.20210002 -0.07031564  0.04236672 -0.09664115]
 [ 0.02703782 -0.1614951  -0.11952763 -0.06893643]
 [ 0.02145514  0.01058503 -0.0162131   0.03067903]
 [-0.08438101  0.16430897  0.19000046 -0.04637727]]


[[0.05875814 0.00118375 0.3646667  0.42547143]
 [0.7879964  0.78384376 0.0673275  0.47886908]
 [0.18715107 0.58080125 0.9571768  0.74377763]
 [0.07165182 0.02295947 0.03756499 0.9948994 ]]




In [0]:
a = tf.constant([[1,2],[3,4]])

In [35]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[10],[100]])

In [42]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a,b)

In [44]:
sess.run(result)

array([[210],
       [430]], dtype=int32)